framework:
    messenger:
        transports:
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            # 'App\Message\YourMessage': async

        default_bus: command.bus
        buses:
            command.bus:
                middleware:
                    - doctrine_transaction
            event.bus:
                default_middleware: allow_no_handlers