parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Model'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Integration/Http/Controller'
        tags: ['controller.service_arguments']

    App\Integration\Database\EventListener\DomainEventListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postFlush }