parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Application\CommandHandler\CommandHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: command.bus }

        App\Application\EventHandler\EventHandlerInterface:
            tags:
                - { name: messenger.message_handler, bus: event.bus }

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/Model'
            - '../src/Kernel.php'

    App\Integration\Http\Controller\:
        resource: '../src/Integration/Http/Controller'
        tags: ['controller.service_arguments']

    App\Integration\Database\EventListener\DomainEventListener:
        tags:
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }
            - { name: doctrine.event_listener, event: postRemove }
            - { name: doctrine.event_listener, event: postFlush }